---
zfs_guard_enabled: true
zfs_guard_pool: "zroot"
zfs_guard_target_role: ""
zfs_guard_target_role_vars: {}

zfs_guard_before_prefix: "before"
zfs_guard_after_prefix: "after"
zfs_guard_timestamp_format: "+%Y%m%d-%H%M%S"

zfs_guard_prune_before_on_nochange: true
zfs_guard_create_after_on_success: true

zfs_guard_live_rollback_on_failure: true
zfs_guard_destroy_before_on_failure: true

zfs_guard_fallback_be_on_rollback_fail: true
zfs_guard_fallback_be_prefix: "rollback"
zfs_guard_auto_reboot_to_fallback_be: false
